/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;

/**
 *
 * @author mateu
 */
public class telaJogo extends javax.swing.JFrame {

    /**
     * Creates new form telaJogo
     */
    public telaJogo() {
        initComponents();
        campo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        a3 = new javax.swing.JSpinner();
        a4 = new javax.swing.JSpinner();
        a5 = new javax.swing.JSpinner();
        a2 = new javax.swing.JSpinner();
        a1 = new javax.swing.JSpinner();
        b1 = new javax.swing.JSpinner();
        d1 = new javax.swing.JSpinner();
        e1 = new javax.swing.JSpinner();
        b2 = new javax.swing.JSpinner();
        b3 = new javax.swing.JSpinner();
        b4 = new javax.swing.JSpinner();
        b5 = new javax.swing.JSpinner();
        c4 = new javax.swing.JSpinner();
        c1 = new javax.swing.JSpinner();
        c2 = new javax.swing.JSpinner();
        c3 = new javax.swing.JSpinner();
        c5 = new javax.swing.JSpinner();
        d2 = new javax.swing.JSpinner();
        d3 = new javax.swing.JSpinner();
        d4 = new javax.swing.JSpinner();
        e4 = new javax.swing.JSpinner();
        e5 = new javax.swing.JSpinner();
        d5 = new javax.swing.JSpinner();
        e2 = new javax.swing.JSpinner();
        e3 = new javax.swing.JSpinner();
        campo = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mensageminicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        start.setForeground(new java.awt.Color(0, 0, 255));
        start.setText("Mostrar Campo");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 130, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 70, -1));

        a3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        a4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        a5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        a2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        a1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        b1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        d1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        e1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        b2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        b3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        b4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        b5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        c4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        c1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        c2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        c3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        c5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        d2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        d3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        d4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        e4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        e5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        d5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        e2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        e3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        campo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/campo.png"))); // NOI18N
        getContentPane().add(campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblFrase.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblFrase.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 332, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/painel.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 230, 190));

        mensageminicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu.png"))); // NOI18N
        mensageminicial.setText("Texto");
        getContentPane().add(mensageminicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 380, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        campo.setVisible(true);
    }//GEN-LAST:event_startActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BLOCO A:
        //a1
        double n = 1 + Math.random() * (5 - 1);
        int valor = (int)n;
        int num = Integer.parseInt(a1.getValue().toString()); //Atribui o valor a NUM     
        String f1 = "ACERTOU";
        String f2 = "ERROU";//Configura as frases        
        String res = (valor == num)?f1:f2;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res);//Mostra o res no balão
        //a2
        double n1 = 1 + Math.random() * (5 - 1);
        int valor1 = (int)n1;
        int num1 = Integer.parseInt(a2.getValue().toString()); 
        String f3 = "ACERTOU";
        String f4 = "ERROU";//Configura as frases        
        String res1 = (valor1 == num1)?f3:f4;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res1);//Mostra o res no balão
        //a3
        double n2 = 1 + Math.random() * (5 - 1);
        int valor2 = (int)n2;
        int num2 = Integer.parseInt(a3.getValue().toString()); 
        String f5 = "ACERTOU";
        String f6 = "ERROU";//Configura as frases        
        String res2 = (valor2 == num2)?f5:f6;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res2);//Mostra o res no balão
        //a4
        double n3 = 1 + Math.random() * (5 - 1);
        int valor3 = (int)n3;
        int num3 = Integer.parseInt(a4.getValue().toString()); 
        String f7 = "ACERTOU";
        String f8 = "ERROU";//Configura as frases        
        String res3 = (valor3 == num3)?f7:f8;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res3);//Mostra o res no balão
        //a5
        double n4 = 1 + Math.random() * (5 - 1);
        int valor4 = (int)n4;
        int num4 = Integer.parseInt(a5.getValue().toString()); 
        String f9 = "ACERTOU";
        String f10 = "ERROU";//Configura as frases        
        String res4 = (valor4 == num4)?f9:f10;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res4);//Mostra o res no balão
        //BLOCO B:
        //b1
        double m = 1 + Math.random() * (5 - 1);
        int valor5 = (int)m;
        int num5 = Integer.parseInt(b1.getValue().toString()); 
        String f11 = "ACERTOU";
        String f12 = "ERROU";//Configura as frases        
        String res5 = (valor5 == num5)?f11:f12;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res5);//Mostra o res no balão
        //b2
        double m1 = 1 + Math.random() * (5 - 1);
        int valor6 = (int)m1;
        int num6 = Integer.parseInt(b2.getValue().toString()); 
        String f13 = "ACERTOU";
        String f14 = "ERROU";//Configura as frases        
        String res6 = (valor6 == num6)?f13:f14;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res6);//Mostra o res no balão
        //b3
        double m2 = 1 + Math.random() * (5 - 1);
        int valor7 = (int)m2;
        int num7 = Integer.parseInt(b3.getValue().toString()); 
        String f15 = "ACERTOU";
        String f16 = "ERROU";//Configura as frases        
        String res7 = (valor7 == num7)?f15:f16;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res7);//Mostra o res no balão
        //b4
        double m3 = 1 + Math.random() * (5 - 1);
        int valor8 = (int)m3;
        int num8 = Integer.parseInt(b4.getValue().toString()); 
        String f17 = "ACERTOU";
        String f18 = "ERROU";//Configura as frases        
        String res8 = (valor8 == num8)?f17:f18;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res8);//Mostra o res no balão
        //b5
        double m4 = 1 + Math.random() * (5 - 1);
        int valor9 = (int)m4;
        int num9 = Integer.parseInt(b5.getValue().toString()); 
        String f19 = "ACERTOU";
        String f20 = "ERROU";//Configura as frases        
        String res9 = (valor9 == num9)?f19:f20;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res9);//Mostra o res no balão
        //BLOCO C:
        //c1
        double l = 1 + Math.random() * (5 - 1);
        int valor10 = (int)l;
        int num10 = Integer.parseInt(c1.getValue().toString()); 
        String f21 = "ACERTOU";
        String f22 = "ERROU";//Configura as frases        
        String res10 = (valor10 == num10)?f21:f22;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res10);//Mostra o res no balão
        //c2
        double l1 = 1 + Math.random() * (5 - 1);
        int valor11 = (int)l1;
        int num11 = Integer.parseInt(c2.getValue().toString()); 
        String f23 = "ACERTOU";
        String f24 = "ERROU";//Configura as frases        
        String res11 = (valor11 == num11)?f23:f24;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res11);//Mostra o res no balão
        //c3
        double l2 = 1 + Math.random() * (5 - 1);
        int valor12 = (int)l2;
        int num12 = Integer.parseInt(c3.getValue().toString()); 
        String f25 = "ACERTOU";
        String f26 = "ERROU";//Configura as frases        
        String res12 = (valor12 == num12)?f25:f26;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res12);//Mostra o res no balão
        //c4
        double l3 = 1 + Math.random() * (5 - 1);
        int valor13 = (int)l3;
        int num13 = Integer.parseInt(c4.getValue().toString()); 
        String f27 = "ACERTOU";
        String f28 = "ERROU";//Configura as frases        
        String res13 = (valor13 == num13)?f27:f28;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res13);//Mostra o res no balão
        //c5
        double l4 = 1 + Math.random() * (5 - 1);
        int valor14 = (int)l4;
        int num14 = Integer.parseInt(c5.getValue().toString()); 
        String f29 = "ACERTOU";
        String f30 = "ERROU";//Configura as frases        
        String res14 = (valor14 == num14)?f29:f30;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res14);//Mostra o res no balão
        //BLOCO D:
        //d1
        double k = 1 + Math.random() * (5 - 1);
        int valor15 = (int)k;
        int num15 = Integer.parseInt(d1.getValue().toString()); 
        String f31 = "ACERTOU";
        String f32 = "ERROU";//Configura as frases        
        String res15 = (valor15 == num15)?f31:f32;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res15);//Mostra o res no balão
        //d2
        double k1 = 1 + Math.random() * (5 - 1);
        int valor16 = (int)k1;
        int num16 = Integer.parseInt(d2.getValue().toString()); 
        String f33 = "ACERTOU";
        String f34 = "ERROU";//Configura as frases        
        String res16 = (valor16 == num16)?f33:f34;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res16);//Mostra o res no balão
        //d3
        double k2 = 1 + Math.random() * (5 - 1);
        int valor17 = (int)k2;
        int num17 = Integer.parseInt(d3.getValue().toString()); 
        String f35 = "ACERTOU";
        String f36 = "ERROU";//Configura as frases        
        String res17 = (valor17 == num17)?f35:f36;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res17);//Mostra o res no balão
        //d4
        double k3 = 1 + Math.random() * (5 - 1);
        int valor18 = (int)k3;
        int num18 = Integer.parseInt(d4.getValue().toString()); 
        String f37 = "ACERTOU";
        String f38 = "ERROU";//Configura as frases        
        String res18 = (valor18 == num18)?f37:f38;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res18);//Mostra o res no balão        
        //d5
        double k4 = 1 + Math.random() * (5 - 1);
        int valor19 = (int)k4;
        int num19 = Integer.parseInt(d5.getValue().toString()); 
        String f39 = "ACERTOU";
        String f40 = "ERROU";//Configura as frases        
        String res19 = (valor19 == num19)?f39:f40;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res19);//Mostra o res no balão        
        //BLOCO E:
        //e1
        double p = 1 + Math.random() * (5 - 1);
        int valor20 = (int)p;
        int num20 = Integer.parseInt(e1.getValue().toString()); 
        String f41 = "ACERTOU";
        String f42 = "ERROU";//Configura as frases        
        String res20 = (valor20 == num20)?f41:f42;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res20);//Mostra o res no balão 
        //e2
        double p1 = 1 + Math.random() * (5 - 1);
        int valor21 = (int)p1;
        int num21 = Integer.parseInt(e2.getValue().toString()); 
        String f43 = "ACERTOU";
        String f44 = "ERROU";//Configura as frases        
        String res21 = (valor21 == num21)?f43:f44;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res21);//Mostra o res no balão 
        //e3
        double p2 = 1 + Math.random() * (5 - 1);
        int valor22 = (int)p2;
        int num22 = Integer.parseInt(e3.getValue().toString()); 
        String f45 = "ACERTOU";
        String f46 = "ERROU";//Configura as frases        
        String res22 = (valor22 == num22)?f45:f46;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res22);//Mostra o res no balão 
        //e4
        double p3 = 1 + Math.random() * (5 - 1);
        int valor23 = (int)p3;
        int num23 = Integer.parseInt(e4.getValue().toString()); 
        String f47 = "ACERTOU";
        String f48 = "ERROU";//Configura as frases        
        String res23 = (valor23 == num23)?f47:f48;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res23);//Mostra o res no balão 
        //e5
        double p4 = 1 + Math.random() * (5 - 1);
        int valor24 = (int)p4;
        int num24 = Integer.parseInt(e5.getValue().toString()); 
        String f49 = "ACERTOU";
        String f50 = "ERROU";//Configura as frases        
        String res24 = (valor24 == num24)?f49:f50;        
        lblFrase.setFont(new Font("Arial", Font.PLAIN,8));        
        lblFrase.setText(res24);//Mostra o res no balão 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner a1;
    private javax.swing.JSpinner a2;
    private javax.swing.JSpinner a3;
    private javax.swing.JSpinner a4;
    private javax.swing.JSpinner a5;
    private javax.swing.JSpinner b1;
    private javax.swing.JSpinner b2;
    private javax.swing.JSpinner b3;
    private javax.swing.JSpinner b4;
    private javax.swing.JSpinner b5;
    private javax.swing.JSpinner c1;
    private javax.swing.JSpinner c2;
    private javax.swing.JSpinner c3;
    private javax.swing.JSpinner c4;
    private javax.swing.JSpinner c5;
    private javax.swing.JLabel campo;
    private javax.swing.JSpinner d1;
    private javax.swing.JSpinner d2;
    private javax.swing.JSpinner d3;
    private javax.swing.JSpinner d4;
    private javax.swing.JSpinner d5;
    private javax.swing.JSpinner e1;
    private javax.swing.JSpinner e2;
    private javax.swing.JSpinner e3;
    private javax.swing.JSpinner e4;
    private javax.swing.JSpinner e5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel mensageminicial;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
